TARGET = infinit limit celsius2fahr fahr2celsius charNumber arithmetics triangle increment literal genderRatio compare compare2 sizeof oddeven fourBit fourBit2
all : ${TARGET}

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celsius : $@
charNumber : $@
arithmetics : $@
triangle : $@
increment : $@
literal : $@
genderRatio : $@
compare : $@
compare2 : $@
sizeof : $@
oddeven : $@
fourBit : $@
fourBit2 : $@

clean :
	rm ${TARGET}