TARGET = swap selection bubble qsort pointerConcept endian pointer2 voidPointer arrayPointer arrayAssignment arrayCompare functionPointer swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2 helloStr charPointerOperation stringExample filePointer fileDescriptor dynamicAllocation charAdress unionExample enumExample
all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerConcept : $@
endian : $@
pointer2 :$@
voidPointer : $@
arrayPointer : $@
arrayAssignment : $@
arrayCompare : $@
functionPointer : $@
swapFunction : $@
sumArrayFunction : $@
sumMatrixFunction : $@
sumMatrixFunction2 : $@
helloStr : $@
charPointerOperation : $@
stringExample : $@
filePointer : $@
fileDescriptor : $@
dynamicAllocation : $@
charAdress : $@
unionExample : $@
enumExample : $@

clean :
	rm ${TARGET}