TARGET = swap selection bubble qsort pointerConcept endian pointer2 voidPointer arrayPointer arrayAssignment arrayCompare functionPointer swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2
all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerConcept : $@
endian : $@
pointer2 :$@
voidPointer : $@
arrayPointer : $@
arrayAssignment : $@
arrayCompare : $@
functionPointer : $@
swapFunction : $@
sumArrayFunction : $@
sumMatrixFunction : $@
sumMatrixFunction2 : $@
clean :
	rm ${TARGET}