TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigLetter one2Ten one2tensum multiplyTable ascii star one2TenWhile one2TenDoWhile randomTwolnt staticLocalVariable functionSum returnValue power dice sumArray sumMatrix findMax findValueArray scoreGrade procScore average2022Temp temp2022 baseball
all : ${TARGET}


absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
posZeroNeg : $2
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiplyTable : $@
ascii : $@
star : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwolnt : $@
staticLocalVariable : $@
functionSum : $@
returnValue : $@
power :$@
dice : $@
sumArray : $@
sumMatrix :$@
findMax : $@
findValueArray : $@
scoreGrade : $@
procScore : $@
average2022Temp : $@
temp2022 : $@
baseball :$@

clean :
	rm ${TARGET}